service:
  image: "sakurlyk/otus:orders_shop"
  replicaCount: 1
  type: ClusterIP
  port: 8000
  fullnameOverride: "orders"

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: "ordersuser"
        password: "orderspasswd"
        database: "ordersdb"
        postgresPassword: "postgres"
      persistence:
        size: 0.1Gi
      service:
        type: ClusterIP
        ports:
          postgresql: "5432"

rabbitmq:
  auth:
    username: "user"
    password: "password"
  host: "rabbitmq"
  service:
    ports:
      amqp: 5672

ingress:
  hosts:
    - host: arch.homework
      paths: ["/orders"]
