apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app-chart.fullname" . }}-servicemonitor
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "app-chart.fullname" . }}
  namespaceSelector:
    matchNames:
    - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "app-chart.selectorLabels" . | nindent 6 }}
  endpoints:
  - interval: 15s
    port: web
    path: /metrics    
    #scrapeTimeout: 30s
    #honorLabels: true
    #scheme: http
