apiVersion: v1
kind: Secret
metadata:
  name: {{ include "delivery-chart.fullname" . }}-secret
data:
  connection_string: {{ printf "User ID=%s;Password=%s;Host=%s;Port=%s;Database=%s"
      .Values.postgresql.global.postgresql.auth.username
      .Values.postgresql.global.postgresql.auth.password
      (include "postgresql.fullname" .)
      .Values.postgresql.global.postgresql.service.ports.postgresql
      .Values.postgresql.global.postgresql.auth.database
    | b64enc
    | quote
  }}
  rabbitmq_password: {{ .Values.rabbitmq.auth.password | b64enc | quote}}
