{
 "title": "CUSTOM DASHBOARD",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request per seconds",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method, exported_endpoint) (rate(http_request_duration_seconds_count{exported_endpoint=~\"/api/v1/users.*\"}[1m])) ",
     "legendFormat": "{{method}} {{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "Latency (0.5)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, method, exported_endpoint) (rate(http_request_duration_seconds_bucket{exported_endpoint=~\"/api/v1/users.*\"}[1m])))",
     "legendFormat": "{{method}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Latency (0.95)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method, exported_endpoint) (rate(http_request_duration_seconds_bucket{exported_endpoint=~\"/api/v1/users.*\"}[1m])))",
     "legendFormat": "{{method}} {{ exported_endpoint }} "
    }
   ]
  },
  {
   "title": "Latency (0.99)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, method, exported_endpoint) (rate(http_request_duration_seconds_bucket{exported_endpoint=~\"/api/v1/users.*\"}[1m])))",
     "legendFormat": "{{method}} {{ exported_endpoint }}"
    }
   ]
  },
  {
   "title": "Latency (max)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le, method, exported_endpoint) (rate(http_request_duration_seconds_bucket{exported_endpoint=~\"/api/v1/users.*\"}[1m])))",
     "legendFormat": "{{method}} {{ exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Errors (4xx and 5xx), %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (method) (rate(http_request_duration_seconds_count{code=~'4..|5..'}[1m]))/sum by (method) (rate(http_request_duration_seconds_count[1m]))*100",
     "legendFormat": "{{ method }} {{ exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Average request time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(method, exported_endpoint) (rate(http_request_duration_seconds_sum{exported_endpoint=~\"/api/v1/users.*\"}[1m])) / sum by(method, exported_endpoint) (rate(http_request_duration_seconds_count{exported_endpoint=~\"/api/v1/users.*\"}[1m]))",
     "legendFormat": "{{method}} {{ exported_endpoint }}"
    }
   ]
  }
 ]
}