apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  connection_string: VXNlciBJRD1wb3N0Z3JlcztQYXNzd29yZD1wZ3Bhc3M7SG9zdD1wb3N0Z3Jlcy1wb3N0Z3Jlc3FsO1BvcnQ9NTQzMjtEYXRhYmFzZT1wb3N0Z3Jlcw==