service:
  image: "sakurlyk/otus:billing_lesson26"
  replicaCount: 1
  type: ClusterIP
  port: 8000
  fullnameOverride: "billing"

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: "billinguser"
        password: "billingpasswd"
        database: "billingdb"
        postgresPassword: "postgres"
      persistence:
        size: 0.1Gi
      service:
        type: ClusterIP
        ports:
          postgresql: "5432"

rabbitmq:
  auth:
    username: "user"
    password: "password"
  #host: "rabbitmq.sakurlyk-lesson26.svc.cluster.local"
  host: "rabbitmq"
  service:
    ports:
      amqp: 5672

ingress:
  hosts:
    - host: arch.homework
      paths: ["/billing"]
