apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "warehouse-chart.fullname" . }}-config
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "Kestrel": {
        "Endpoints": {
          "Http": {
            "Url": "http://*:8000"
          }
        }
      }
    }
