apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "warehouse-chart.fullname" . }}-ingress
  labels:
    {{- include "warehouse-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  {{- $fullName := include "warehouse-chart.fullname" . -}}
  {{- $svcPort := .Values.service.port -}}
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}($|/)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
        {{- end }}
  {{- end }}
